<?php

echo "
<html>
<head>
<title>AphroBall Administration </title>
<style type=\"text/css\">
<!--
.title5 { font-weight: bold; font-size:12pt; color:#ff6600; font-family:verdana}
.title7 {font-size:11pt; color:#ff6600; font-family:verdana}
.title9 {font-size:8pt; color:#000000; font-family:verdana}
.noline { text-decoration:none; }
.archive {font-family:arial; font-size:9pt; color:orange}
.header1 {font-family:arial; font-size:9pt; color:purple}
.header2 {font-family:arial; font-size:9pt;}
.signature {font-family:brush script; font-size:20pt; color:blue;}
//-->
</style>
";
include_once("analyticstracking.php");
echo "
</head>

<body bgcolor=\"#FFFFFF\">";


   // check to see if the cookie is set
   $val = $_COOKIE['User'];
   if (!isset($val)) {
      $_COOKIE['User'] = "Guest";
   }
   $newVal = $_COOKIE['User'];

   $scores = $_POST['wscores'];
   $email  = $_POST['email'];
   $mpicks = $_POST['mpicks'];

   $sendTo      = "";
   $email_header = "";
   $emailPrint  = 0;
   $mpicksPrint = 0;

   if ($week == NULL) {
      include("weekSelector.inc");
   }
   //echo "Which week:$week<br>";

   // open the database
   //$db = mysql_connect("localhost", "root", "hoosier");
   //mysql_select_db("aphroball_2015",$db);
   include 'database.php';

   //extract list of users from the admin table
   $users = mysql_query("SELECT * FROM admin",$db);
   $num_users = mysql_num_rows($users);

   //echo "-num-$num_users<br>\n";
   //send an email only to the players who have not made their picks for the week yet.
   if ($email) {

      for ($p=1;$p<=$num_users;$p++) {

         //fetch a new entry from the admin table each time
         $cur_user = mysql_fetch_array($users);

         //make the row yellow for the user who is looking at this page
         $user   = $cur_user["userid"];
         //echo "-$user-<br>";
         if ($user == "guest") {
           $cur_user = mysql_fetch_array($users);
           $p++;
         }
         //in case it was the guest, we need to re-enter this value
         $user   = $cur_user["userid"];

         //echo "SELECT * FROM $user WHERE week=$week<br>";
         $checkPicksQ = mysql_query("SELECT * FROM $user WHERE week=\"$week\"",$db);
         $checkPicks  = mysql_num_rows($checkPicksQ);

         //echo "-$checkPicks-$user-<br>";

         if ($checkPicks == 0) {

            $sendTo .= $cur_user["email"];
            $sendTo .= ", ";

         }//end if ($checkPicks) loop
      }  // end for loop
      $sendTo .= "aphroadmin@aphroball.com";

      $message = "
*****************************
This is an automated response
so don't reply to this address
*****************************\n

You are getting this email because it appears you have not
yet submitted your picks for Week $week


Please log on to make your picks.\n
http://www.aphroball.com/AphroBall2015/aphrohome.php\n

If you have submitted them, then an error occurred on the server side of the website
and your picks never made it to the server.  You can either resubmit your picks on
the website, or send the email that was generated by the website to aphroadmin@aphroball.com";

      //$subject = "Your AphroBall picks for Week $week have not been submitted";
      $subject = "NOTE: Picks must be in by 7:00pm CST on THURSDAY for Week $week";
      $email_header .= "From: AphroBall Administration <aphroadmin@aphroball.com>\n";
      $email_header .= "Reply-To: aphroadmin@aphroball.com\n";
      $email_header .= "Content-transfer-encoding: 7bit\n";
      $email_header .= "Content-type: text/plain; charset=\"iso-8859-1\"\r\n";

      //$sendTo = "ryan.x.miller@seagate.com";
      echo "-$sendTo<br>-$subject<br>-";
      //$rc = mail($sendTo, $subject, $message, $email_header);

      if ($rc) {
         $emailPrint = 1;
      }
      else {
         $emailPrint = 0;
      }

   } //end if ($email) loop

   //enter this loop if we want to automagically update them with the visitors by 3 points
   if ($mpicks) {

      for ($p=1;$p<=$num_users;$p++) {

         //fetch a new entry from the admin table each time
         $cur_user = mysql_fetch_array($users);

         //make the row yellow for the user who is looking at this page
         $user   = $cur_user["userid"];
         //echo "-$user-<br>";
         if ($user == "guest") {
           $cur_user = mysql_fetch_array($users);
           $p++;
         }
         //in case it was the guest, we need to re-enter this value
         $user   = $cur_user["userid"];

         $checkPicksQ = mysql_query("SELECT * FROM $user WHERE week=\"$week\"",$db);
         $checkPicks  = mysql_num_rows($checkPicksQ);

         //echo "-$checkPicks-$user-week<$week><br>";
         if ($checkPicks == 0) {

            $schedQ = mysql_query("SELECT * FROM schedule2015 WHERE week=\"$week\" ORDER BY gamenum",$db);
            $sched  = mysql_fetch_array($schedQ);
            $schedG = mysql_num_rows($schedQ);

            //update their picks with this loop
            for ($i=1;$i<=$schedG;$i++) {

               $winner = $sched["visitor"];
               $input = mysql_query("INSERT INTO $user VALUES (\"$week\", \"$i\", \"$winner\",
                                        \"3\", \"0\", \"0\", \"0\", \"1\")", $db);

               //echo "INSERT INTO $user VALUES (\"$week\", \"$i\", \"$winner\",
                                       // \"3\", \"0\", \"0\", \"0\", \"1\")<br>";

               $sched  = mysql_fetch_array($schedQ);

            }

         }//end if ($checkPicks) loop
      }  // end for loop

   }


   echo "

<center>
<table width=800 border=0 cellspacing=0 cellpadding=0>
<tr>
   <td>&nbsp;</td>
   <td align=right><font size=-1>Welcome <b>$newVal</b></font> /
         <font size=-2><b>[<a href=\"logout.php\" class=noline>LogOut</a>]</b></font> </td>
</tr>
<tr>
   <td colspan=2><hr></td>
</tr>
<tr>

   <td valign=top>&nbsp;<br>&nbsp;<br><table width=150 border=0 bgcolor=\"#EEEEEE\">
       <tr>
          <td><a href=\"aphrohome.php\" class=noline> &nbsp;Home</a><br>
          <a href=\"rules.php\" class=noline> &nbsp;Rules</a><br>
          <a href=\"blog.php\" class=noline> &nbsp;Message Board</a><br>
          <a href=\"week.php\" class=noline> &nbsp;Make Your Picks</a><br>
          <a href=\"results.php\" class=noline> &nbsp;Results</a><br>
          <a href=\"weekSorter.php\" class=noline> &nbsp;Performance</a><br>
          <hr width=75%>
          <a href=\"members.php\" class=noline> &nbsp;AphroBall Members</a><br>
          <a href=\"na.php\" class=noline> &nbsp;Founding Fathers</a><br>
          <a href=\"na.php\" class=noline> &nbsp;Archive</a><br>
          <p> &nbsp;
          </td>
       </tr>
       </table>
   </td>
   <td valign=top><p>&nbsp;\n";
   if ($email) {
      //depending on whether the mailer worked, print out a different message.
      if ($emailPrint) {
       echo "    <strong>Email has been sent</strong><br>\n";
      }
      else {
       echo "    <strong>There was a problem with the email server and an email was not sent</strong>.<br>\n";
      }
   }
   if ($mpicks) {
       echo "    <strong>Default picks have been made</strong><br>\n";
   }
echo "
   <form name=\"scores\" method=POST action=\"weeklyScores.php\">
   <p><input type=submit name=\"wscores\" value=\"Enter Scores\"> : Enter the weekly scores
   </form>

   <form name=\"semail\" method=POST action=$PHP_SELF>
   <p><input type=submit name=\"email\" value=\"Send Email\"> : Send out email to those who have not yet made their picks
   </form>

   <form name=\"picks\" method=POST action=$PHP_SELF>
   <p><input type=submit name=\"mpicks\" value=\"Make Picks\"> : Make default picks for the players who forgot
   </form>
  </td>

</tr>
</table> </center>


</body>
</html>";

?>
